---
- name: Create EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    host_file: "./hosts"

  tasks:
    - name: Delete the old hosts file
      file:
        path: "{{host_file}}"
        state: absent
      tags: test

    - name: start an instance master with a privateIP address
      amazon.aws.ec2_instance:
        name: "k8s-master"
        key_name: "infra-systems-nonprod-key"
        vpc_subnet_id: subnet-0a166fdea2d239f7d
        instance_type: t3.micro
        security_group: "sg-07087fd9a2a298f1e"
        count: 1
        network:
          assign_public_ip: false
        image_id: ami-0557a15b87f6559cf
        tags:
          Environment: Testing
          Name: k8s-master-test
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 60
              delete_on_termination: true
      register: ec2_master

    - name: Create worker instances
      amazon.aws.ec2_instance:
        name: "k8s-worker"
        key_name: "infra-systems-nonprod-key"
        vpc_subnet_id: subnet-0a166fdea2d239f7d
        instance_type: t3.micro
        security_group: "sg-07087fd9a2a298f1e"
        count: 2
        network:
          assign_public_ip: false
        image_id: ami-0557a15b87f6559cf
        tags:
          Environment: Testing
          Name: k8s-worker-test
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 60
              delete_on_termination: true
      register: ec2_worker

    - name: Add cluster group name to the file
      lineinfile:
        path: "{{host_file}}"
        line: "[k8s_cluster]"
        create: yes

    - name: Add master instances to k8s host group
      lineinfile:
        path: "{{host_file}}"
        insertafter: "[k8s_cluster]"
        line: "{{ item.private_ip_address}}"
      with_items: "{{ ec2_master.instances }}"

    - name: Add worker instances to k8s host group
      lineinfile:
        path: "{{host_file}}"
        insertafter: "[k8s_cluster]"
        line: "{{ item.private_ip_address}}"
      with_items: "{{ ec2_worker.instances }}"

    - name: Add master group
      lineinfile:
        path: "{{host_file}}"
        line: "[k8s_master]"
        create: yes
      tags: test

    - name: Add worker group
      lineinfile:
        path: "{{host_file}}"
        line: "[k8s_worker]"
        create: yes
      tags: test

    - name: Add master instances to k8s master host group
      shell: sed -i "/k8s_master/a \{{item.private_ip_address}}" "{{host_file}}"
      with_items: "{{ ec2_master.instances }}"

    - name: Add worker instances to k8s worker host group
      shell: sed -i "/k8s_worker/a \{{item.private_ip_address}}" "{{host_file}}"
      with_items: "{{ec2_worker.instances}}"

    - name: Wait for SSH(master instance) to come up
      wait_for:
        host: "{{ item.private_ip_address }}"
        port: 22
      with_items: "{{ ec2_master.instances }}"

    - name: Wait for SSH(worker instance) to come up
      wait_for:
        host: "{{ item.private_ip_address }}"
        port: 22
      with_items: "{{ ec2_worker.instances }}"
