apiVersion: apps/v1 
kind: Deployment
metadata:
  name: devapp-deployment
  labels: 
     app: devapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: devapp

  template:
    metadata:
      labels:
        app: devapp
    spec:
      affinity:
       podAntiAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
         - labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
               - devapp
           topologyKey: "kubernetes.io/hostname"
   
    
      containers:
      - name: devapp
        image: nethramurali/devapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
