- name: Started Installation Kubernetes
  hosts: localhost
  become: yes
  become_user: root

  tasks:
    - name: Include Preparing Yml File To Prepare Machines
      include: tasks/prerequistes.yml

    - name: Include Preparing Yml File To Prepare Machines
      include: tasks/iptablesandcgroupdriver.yml

    - name: Include Master Yml File To Set Master Machine
      include: tasks/master_nodesetup.yml

    - name: Include Initiate Yml File To Join Worker Node
      include: tasks/worker_node_joining.yml
