---
- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: Get the token for joining the worker nodes
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: set join command
      set_fact:
        join_command: "{{  kubernetes_join_command.stdout_lines[0] }}"

    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
