---
 - name: create kubernetes cluster master node setup
   hosts: master,worker
   become: yes
   tasks:
     - name: Copying Kubernetes Repo file
       copy:
         src: ./kubernetes.repo
         dest: /etc/yum.repos.d/kubernetes.repo
         mode: '0644'

     - name: enable kubelet
       shell: |
         sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
         systemctl enable kubelet
         systemctl start kubelet
