---
 - name: joining the worker node to the master
   hosts: worker
   become: yes
   gather_facts: yes

   tasks:
    - name: Copy join command from Ansiblehost to the worker nodes.
      become: yes
      copy:
       src: /root/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777

    - name: Join the Worker nodes to the cluster.
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not
